#!/usr/bin/env python3

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('nm', type=float, help='Energy in nm to convert into eV')
    args = parser.parse_args()
    plank = 6.62607015e-34
    c = 299792458
    e = 1.602177e-19
    eV = round((c*plank)/(args.nm*e)*1e9, 5)
    cm = round(1/args.nm * 10e6, 2)
    print(eV, 'eV')
    print(cm, 'cm-1')


if __name__ == '__main__':
    main()
