#!/bin/bash

# Download stuff from NERSC
rsync --copy-links -avzu --exclude h2o_uhf.tar --exclude eu_uhf.tar --exclude "*.int" --exclude "scratch" --exclude "sww" --del -e "ssh -l taras -i /Users/taras/.ssh/nersc" perlmutter.nersc.gov:/global/homes/t/taras/work/ /Users/taras/work/nersc/ 
