#!/bin/bash

rsync -e ssh -a nersc:/global/homes/t/taras/work/ /home/taras/work/nersc \
--exclude="*.chk" \
--exclude="*.tmp*" \
--exclude="*.tmp" \
--exclude="*.rwf" \
--exclude="*.fchk" \
--progress \
--update \
