#!/bin/bash


rsync -e ssh -a bridges2.psc.edu:/ocean/projects/che230036p/khvorost/azo /home/taras/work/bri/ \
--exclude="*.chk" \
--exclude="*.rwf" \
--exclude="*.tmp*" \
--exclude="*.tmp" \
--exclude="*.fchk" \
--progress \
--update \

#rsync -e ssh -a bridges2.psc.edu:/ocean/projects/che230036p/khvorost/cat /home/taras/work/bri/ \
#--exclude="*.chk" \
#--exclude="*.tmp*" \
#--exclude="*.tmp" \
#--exclude="*.rwf" \
#--exclude="*.fchk" \
#--progress \
#--update \

#rsync -e ssh -a bridges2.psc.edu:/ocean/projects/che230036p/khvorost/ph /home/taras/work/bri/ \
#--exclude="*.chk" \
#--exclude="*.tmp*" \
#--exclude="*.tmp" \
#--exclude="*.rwf" \
#--exclude="*.fchk" \
#--progress \
#--update \

#rsync -e ssh -a bridges2.psc.edu:/ocean/projects/che230036p/khvorost/ada /home/taras/work/bri/ \
#--exclude="*.chk" \
#--exclude="*.tmp*" \
#--exclude="*.tmp" \
#--exclude="*.rwf" \
#--exclude="*.fchk" \
#--progress \
#--update \

rsync -e ssh -a bridges2.psc.edu:/ocean/projects/che230036p/khvorost/yb /home/taras/work/bri/ \
--exclude="*.chk" \
--exclude="*.tmp*" \
--exclude="*.tmp" \
--exclude="*.rwf" \
--exclude="*.fchk" \
--progress \
--update \







