#!/bin/bash


rsync  \
      -rltppv -hu \
      --exclude "fort.7" \
      --exclude "*.fchk" \
      --exclude "old.tar" \
      --exclude "quantics" \
      --exclude "*.com" \
      --exclude ".git" \
      --exclude "*.sh" \
      --exclude "bdf" \
      --exclude "cas" \
      --exclude "*.gjf" \
      --exclude "Gau*" \
      --exclude "core*" \
      --exclude "*.rwf" \
      --exclude "*.chk" \
      khvorost@bridges2.psc.edu:/ocean/projects/che230036p/khvorost/ /Users/taras/work/bri

