#!/opt/homebrew/bin/python3

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('cm', type=float, help='Energy in cm-1 to convert')
    args = parser.parse_args()
    plank = 6.62607015e-34
    c = 299792458
    e = 1.602177e-19
    wavelength = round(1.00/args.cm * 1e7, 2)
    const = (plank * c)/e
    eV = round(args.cm * const * 1e2, 3)
    print(wavelength, 'nm')
    print(eV, 'eV')


if __name__ == '__main__':
    main()
