#!/usr/bin/python3
import os
import sys

def parse_args():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('geom', help='xyz file with the starting geom', type=open)
    parser.add_argument('-o', default=sys.stdout, type=argparse.FileType('w'))
    parser.add_argument('-s', default=2, type=int)
    parser.add_argument('-p', action='store_true')
    parser.add_argument('-basis', default=os.environ['HOME']+'/.basis/ca-och', type=open)
    args = parser.parse_args()

    if args.p:
        args.p = '_p'
    else:
        args.p = ''
    args.basis.close()
    args.basis = os.path.abspath(args.basis.name)
    args.text = args.geom.readlines()
    args.path = os.path.abspath(args.geom.name)
    args.geom.close()

    return args

def create_pipe(args):
    print("""
#!/bin/bash

set -e
SCRIPT_DIR=$(dirname $(readlink -f $0))
cd $SCRIPT_DIR
    """, file=args.o)
    print(f'export basis={args.basis}', file=args.o)
    print(f'mkdir -p es1/ es2/ es3/ es4/ es5/ fcf/', file=args.o)
    print(f'cat ~/.route/gs{args.p} | gci {args.path} -o gs.inp -basis $basis -s{args.s}', file=args.o)
    print('sgaus gs.inp -o gs.sh -t10', file=args.o)
    print("""
cat << EOF >> gs.sh
set -e

pushd fcf
ln -s ../gs.chk ./gs.chk
popd

# TDDFT
cat ~/.route/tddft | gci gs.out -o tddft.inp -basis $basis
sgaus tddft.inp -o tddft.sh -t10 -R

# EXCITED STATES

for i in {1..3}; do

    cat ~/.route/es${i}{args.p} | gci gs.out -o es${i}/es${i}.inp -basis $basis
    touch es${i}/es${i}_freq.inp
    sgaus es$i/es${i}.inp -o es${i}/es${i}.sh 
    sgaus es${i}/es${i}_freq.inp -o es${i}/es${i}_freq.sh

    echo "cat ~/.route/es${i}_freq | gci es${i}.out -o es${i}_freq.inp -basis $basis" >> es${i}/es${i}.sh
    echo "sbatch es${i}_freq.sh"                                                      >> es${i}/es${i}.sh
    echo "pushd ../fcf"                                                               >> es${i}/es${i}_freq.sh
    echo "ln -s ../es${i}/es${i}_freq.chk ./es${i}.chk"                               >> es${i}/es${i}_freq.sh
    echo "fcf gs.chk es${i}.chk -s 3 > fcf${i}.inp"                                   >> es${i}/es${i}_freq.sh
    echo "g16 < fcf${i}.inp > fcf${i}.out"                                            >> es${i}/es${i}_freq.sh
    echo "popd"                                                                       >> es${i}/es${i}_freq.sh


    sbatch es${i}/es${i}.sh
done

EOF
sbatch gs.sh
    """, file=args.o)
    args.o.close()

def main():
    args = parse_args()
    create_pipe(args)

if __name__ == '__main__':
    main()
